export const FETCH_PRODUCT_FEATURED_REQUEST = "FETCH_PRODUCT_FEATURED_REQUEST";
export const FETCH_PRODUCT_FEATURED_SUCCESS = "FETCH_PRODUCT_FEATURED_SUCCESS";
export const FETCH_PRODUCT_FEATURED_FAIL = "FETCH_PRODUCT_FEATURED_FAIL";

export const FETCH_PRODUCT_CATEGORIES_DRINKS_REQUEST =
  "FETCH_PRODUCT_CATEGORIES_DRINKS_REQUEST";
export const FETCH_PRODUCT_CATEGORIES_DRINKS_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_DRINKS_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_DRINKS_FAIL =
  "FETCH_PRODUCT_CATEGORIES_DRINKS_FAIL";

export const FETCH_PRODUCT_CATEGORIES_BOTTLEDCANNED_REQUEST =
  "FETCH_PRODUCT_CATEGORIES_REQUEST";
export const FETCH_PRODUCT_CATEGORIES_BOTTLEDCANNED_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_BOTTLEDCANNED_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_BOTTLEDCANNED_FAIL =
  "FETCH_PRODUCT_CATEGORIES_BOTTLEDCANNED_FAIL";

export const FETCH_PRODUCT_CATEGORIES_NOODLES_REQUEST =
  "FETCH_PRODUCT_CATEGORIES_NOODLES_REQUEST";
export const FETCH_PRODUCT_CATEGORIES_NOODLES_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_NOODLES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_NOODLES_FAIL =
  "FETCH_PRODUCT_CATEGORIES_NOODLES_FAIL";

export const FETCH_PRODUCT_CATEGORIES_RICEGRAINS_REQUEST =
  "FETCH_PRODUCT_CATEGORIES_RICEGRAINS_REQUEST";
export const FETCH_PRODUCT_CATEGORIES_RICEGRAINS_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_RICEGRAINS_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_RICEGRAINS_FAIL =
  "FETCH_PRODUCT_CATEGORIES_RICEGRAINS_FAIL";

export const FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_REQUEST =
  "FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_REQUEST";
export const FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_FAIL =
  "FETCH_PRODUCT_CATEGORIES_SAUCESSEASONINGS_FAIL";

// USER
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
