export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_SAVE_PRODUCTS = "CART_SAVE_PRODUCTS";
export const CART_SAVE_PRICE_DETAILS = "CART_SAVE_PRICE_DETAILS";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT_DETAILS = "CART_SAVE_PAYMENT_DETAILS";
export const CART_LIST_CLEAR = "CART_LIST_CLEAR";
