export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_SAVE_LOCATION = "ORDER_SAVE_LOCATION";

export const ORDER_SAVE_PRODUCTS = "ORDER_SAVE_PRODUCTS";

export const ORDER_SAVE_PRICE_DETAILS = "ORDER_SAVE_PRICE_DETAILS";

export const ORDER_SAVE_PAYMENT_DETAILS = "ORDER_SAVE_PAYMENT_DETAILS";

export const ORDER_LIST_CLEAR = "ORDER_LIST_CLEAR";
