export const FETCH_PRODUCTS_FEATURED_REQUEST = "FETCH_PRODUCT_FEATURED_REQUEST";
export const FETCH_PRODUCTS_FEATURED_SUCCESS = "FETCH_PRODUCT_FEATURED_SUCCESS";
export const FETCH_PRODUCTS_FEATURED_FAIL = "FETCH_PRODUCT_FEATURED_FAIL";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_PRODUCT_ID_REQUEST = "FETCH_PRODUCT_ID_REQUEST";
export const FETCH_PRODUCT_ID_SUCCESS = "FETCH_PRODUCT_ID_SUCCESS";
export const FETCH_PRODUCT_ID_FAIL = "FETCH_PRODUCT_ID_FAIL";

export const FETCH_ADVERTISEMENT_REQUEST = "FETCH_ADVERTISEMENT_REQUEST";
export const FETCH_ADVERTISEMENT_SUCCESS = "FETCH_ADVERTISEMENT_SUCCESS";
export const FETCH_ADVERTISEMENT_FAIL = "FETCH_ADVERTISEMENT_FAIL";

export const FETCH_PRODUCTS_SEARCH_REQUEST = "FETCH_PRODUCTS_SEARCH_REQUEST";
export const FETCH_PRODUCTS_SEARCH_SUCCESS = "FETCH_PRODUCTS_SEARCH_SUCCESS";
export const FETCH_PRODUCTS_SEARCH_FAIL = "FETCH_PRODUCTS_SEARCH_FAIL";
